### ISSUE TITLE
feat(calls): add option to change Audio/Video sample rate of the incoming stream

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-Backlog#7]
**Tasks**
- [ ] Add option to change audio/video sample rate of incoming stream
- [ ] Use a default codec and sample rate
- [ ] Have a "low bandwidth" sample rate which can be requested
